Instala as Bibliotecas

In [119]:
pip install pandas

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [120]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (2.0.43)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [121]:
pip install psycopg2

Requirement already satisfied: psycopg2 in /opt/homebrew/anaconda3/envs/data-ai-env/lib/python3.11/site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

Importar as Bibliotecas

In [122]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.min_rows", 20)

from sqlalchemy import create_engine
from datetime import datetime, timedelta
import time

Definir função para buscar os Dados

In [123]:
def busca_titulos_tesouro_direto():
    url = 'https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/PrecoTaxaTesouroDireto.csv'
    df = pd.read_csv(url, sep=';', decimal=',')
    df['Data_Vencimento'] = pd.to_datetime(df['Data Vencimento'], dayfirst=True)
    df['Data_Base'] = pd.to_datetime(df['Data Base'], dayfirst=True)
    multi_indice = pd.MultiIndex.from_frame(df.iloc[:,:3])
    df = df.set_index(multi_indice).iloc[:, 3:]
    return df

Busca os títulos do Tesouro Direto

In [124]:
titulos = busca_titulos_tesouro_direto()

In [125]:
titulos

                                                                   Taxa Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007               6.81
                                       01/07/2017      26/10/2007               7.17
                                       01/03/2011      26/10/2007               7.31
                                       01/04/2008      26/10/2007               6.11
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007              11.90
                                       01/01/2010      26/10/2007              11.78
                                       01/01/2008      26/10/2007              11.16
                                       01/01/2011      26/10/2007              11.93
                                       01/01/2012      26/10/2007              11.92
                                       01/01/2013      26/10/2007              11.99
...                                                                              ...
Tesouro Selic                          07/03/2014      15/08/2011               0.00
Tesouro Prefixado                      01/01/2013      15/08/2011              11.95
                                       01/01/2014      15/08/2011              12.05
                                       01/01/2015      15/08/2011              12.13
                                       01/01/2012      15/08/2011              12.32
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011               6.45
                                       15/05/2017      15/08/2011               6.45
                                       15/05/2045      15/08/2011               6.14
                                       15/08/2024      15/08/2011               6.31
                                       15/05/2035      15/08/2011               6.22

                                                                   Taxa Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007              6.89
                                       01/07/2017      26/10/2007              7.23
                                       01/03/2011      26/10/2007              7.35
                                       01/04/2008      26/10/2007              6.13
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007             11.96
                                       01/01/2010      26/10/2007             11.84
                                       01/01/2008      26/10/2007             11.19
                                       01/01/2011      26/10/2007             11.99
                                       01/01/2012      26/10/2007             11.98
                                       01/01/2013      26/10/2007             12.05
...                                                                             ...
Tesouro Selic                          07/03/2014      15/08/2011              0.03
Tesouro Prefixado                      01/01/2013      15/08/2011             11.99
                                       01/01/2014      15/08/2011             12.11
                                       01/01/2015      15/08/2011             12.19
                                       01/01/2012      15/08/2011             12.35
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011              6.51
                                       15/05/2017      15/08/2011              6.51
                                       15/05/2045      15/08/2011              6.24
                                       15/08/2024      15/08/2011              6.39
                                       15/05/2035      15/08/2011              6.32

                                                                   PU Compra Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007          1861.80
                                       01/07/2017      26/10/2007          1870.73
                                       01/03/2011      26/10/2007          1932.23
                                       01/04/2008      26/10/2007          1995.20
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007           992.48
                                       01/01/2010      26/10/2007          1000.20
                                       01/01/2008      26/10/2007          1030.04
                                       01/01/2011      26/10/2007           984.79
                                       01/01/2012      26/10/2007           973.62
                                       01/01/2013      26/10/2007           961.00
...                                                                            ...
Tesouro Selic                          07/03/2014      15/08/2011          4819.19
Tesouro Prefixado                      01/01/2013      15/08/2011           856.42
                                       01/01/2014      15/08/2011           763.04
                                       01/01/2015      15/08/2011           679.03
                                       01/01/2012      15/08/2011           957.14
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011          2001.04
                                       15/05/2017      15/08/2011          2049.31
                                       15/05/2045      15/08/2011          2055.65
                                       15/08/2024      15/08/2011          2008.51
                                       15/05/2035      15/08/2011          2040.53

                                                                   PU Venda Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007         1849.01
                                       01/07/2017      26/10/2007         1863.18
                                       01/03/2011      26/10/2007         1930.05
                                       01/04/2008      26/10/2007         1995.05
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007          991.25
                                       01/01/2010      26/10/2007          999.16
                                       01/01/2008      26/10/2007         1029.99
                                       01/01/2011      26/10/2007          983.37
                                       01/01/2012      26/10/2007          971.86
                                       01/01/2013      26/10/2007          958.95
...                                                                           ...
Tesouro Selic                          07/03/2014      15/08/2011         4815.50
Tesouro Prefixado                      01/01/2013      15/08/2011          856.00
                                       01/01/2014      15/08/2011          762.07
                                       01/01/2015      15/08/2011          677.80
                                       01/01/2012      15/08/2011          957.05
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011         1993.11
                                       15/05/2017      15/08/2011         2043.71
                                       15/05/2045      15/08/2011         2027.75
                                       15/08/2024      15/08/2011         1994.73
                                       15/05/2035      15/08/2011         2016.38

                                                                   PU Base Manha  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007        1846.94
                                       01/07/2017      26/10/2007        1861.06
                                       01/03/2011      26/10/2007        1927.85
                                       01/04/2008      26/10/2007        1992.87
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007         990.80
                                       01/01/2010      26/10/2007         998.72
                                       01/01/2008      26/10/2007        1029.56
                                       01/01/2011      26/10/2007         982.92
                                       01/01/2012      26/10/2007         971.42
                                       01/01/2013      26/10/2007         958.52
...                                                                          ...
Tesouro Selic                          07/03/2014      15/08/2011        4813.25
Tesouro Prefixado                      01/01/2013      15/08/2011         855.62
                                       01/01/2014      15/08/2011         761.72
                                       01/01/2015      15/08/2011         677.49
                                       01/01/2012      15/08/2011         956.60
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011        1992.43
                                       15/05/2017      15/08/2011        2043.02
                                       15/05/2045      15/08/2011        2027.08
                                       15/08/2024      15/08/2011        1994.06
                                       15/05/2035      15/08/2011        2015.71

                                                                  Data_Vencimento  \
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007      2021-04-01
                                       01/07/2017      26/10/2007      2017-07-01
                                       01/03/2011      26/10/2007      2011-03-01
                                       01/04/2008      26/10/2007      2008-04-01
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007      2010-07-01
                                       01/01/2010      26/10/2007      2010-01-01
                                       01/01/2008      26/10/2007      2008-01-01
                                       01/01/2011      26/10/2007      2011-01-01
                                       01/01/2012      26/10/2007      2012-01-01
                                       01/01/2013      26/10/2007      2013-01-01
...                                                                           ...
Tesouro Selic                          07/03/2014      15/08/2011      2014-03-07
Tesouro Prefixado                      01/01/2013      15/08/2011      2013-01-01
                                       01/01/2014      15/08/2011      2014-01-01
                                       01/01/2015      15/08/2011      2015-01-01
                                       01/01/2012      15/08/2011      2012-01-01
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011      2020-08-15
                                       15/05/2017      15/08/2011      2017-05-15
                                       15/05/2045      15/08/2011      2045-05-15
                                       15/08/2024      15/08/2011      2024-08-15
                                       15/05/2035      15/08/2011      2035-05-15

                                                                   Data_Base
Tipo Titulo                            Data Vencimento Data Base
Tesouro IGPM+ com Juros Semestrais     01/04/2021      26/10/2007 2007-10-26
                                       01/07/2017      26/10/2007 2007-10-26
                                       01/03/2011      26/10/2007 2007-10-26
                                       01/04/2008      26/10/2007 2007-10-26
Tesouro Prefixado com Juros Semestrais 01/07/2010      26/10/2007 2007-10-26
                                       01/01/2010      26/10/2007 2007-10-26
                                       01/01/2008      26/10/2007 2007-10-26
                                       01/01/2011      26/10/2007 2007-10-26
                                       01/01/2012      26/10/2007 2007-10-26
                                       01/01/2013      26/10/2007 2007-10-26
...                                                                      ...
Tesouro Selic                          07/03/2014      15/08/2011 2011-08-15
Tesouro Prefixado                      01/01/2013      15/08/2011 2011-08-15
                                       01/01/2014      15/08/2011 2011-08-15
                                       01/01/2015      15/08/2011 2011-08-15
                                       01/01/2012      15/08/2011 2011-08-15
Tesouro IPCA+ com Juros Semestrais     15/08/2020      15/08/2011 2011-08-15
                                       15/05/2017      15/08/2011 2011-08-15
                                       15/05/2045      15/08/2011 2011-08-15
                                       15/08/2024      15/08/2011 2011-08-15
                                       15/05/2035      15/08/2011 2011-08-15

[172598 rows x 7 columns]

Busca somente os Préfixados

In [126]:
prefixado = titulos.loc[('Tesouro Prefixado')]
prefixado['Tipo'] = "PRE-FIXADOS"

/var/folders/cx/md507_zx4ybf51hwf3zqkzbh0000gn/T/ipykernel_47192/2914005242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado['Tipo'] = "PRE-FIXADOS"

In [127]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/07/2008      25/10/2007              11.34             11.38
01/01/2008      25/10/2007              11.16             11.19
01/01/2009      25/10/2007              11.54             11.58
01/07/2009      25/10/2007              11.73             11.78
01/10/2009      25/10/2007              11.77             11.82
01/01/2010      25/10/2007              11.77             11.83
01/10/2008      25/10/2007              11.45             11.49
01/04/2008      25/10/2007              11.23             11.26
01/10/2009      24/10/2007              11.66             11.71
01/07/2009      24/10/2007              11.61             11.66
...                                       ...               ...
01/01/2014      17/08/2011              11.97             12.03
01/01/2015      17/08/2011              12.02             12.08
                16/08/2011              12.10             12.16
01/01/2013      16/08/2011              11.97             12.01
01/01/2012      16/08/2011              12.34             12.37
01/01/2014      16/08/2011              12.02             12.08
01/01/2013      15/08/2011              11.95             11.99
01/01/2014      15/08/2011              12.05             12.11
01/01/2015      15/08/2011              12.13             12.19
01/01/2012      15/08/2011              12.32             12.35

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/07/2008      25/10/2007           931.28          931.06         930.66
01/01/2008      25/10/2007           981.69          981.65         981.23
01/01/2009      25/10/2007           878.84          878.47         878.08
01/07/2009      25/10/2007           831.22          830.60         830.23
01/10/2009      25/10/2007           807.22          806.52         806.17
01/01/2010      25/10/2007           785.07          784.16         783.81
01/10/2008      25/10/2007           904.62          904.32         903.93
01/04/2008      25/10/2007           956.62          956.51         956.11
01/10/2009      24/10/2007           808.39          807.70         807.34
01/07/2009      24/10/2007           832.34          831.72         831.36
...                                     ...             ...            ...
01/01/2014      17/08/2011           765.02          764.05         763.71
01/01/2015      17/08/2011           681.90          680.67         680.36
                16/08/2011           679.95          678.73         678.42
01/01/2013      16/08/2011           856.59          856.18         855.79
01/01/2012      16/08/2011           957.52          957.42         956.98
01/01/2014      16/08/2011           763.87          762.90         762.55
01/01/2013      15/08/2011           856.42          856.00         855.62
01/01/2014      15/08/2011           763.04          762.07         761.72
01/01/2015      15/08/2011           679.03          677.80         677.49
01/01/2012      15/08/2011           957.14          957.05         956.60

                           Data_Vencimento  Data_Base         Tipo
Data Vencimento Data Base
01/07/2008      25/10/2007      2008-07-01 2007-10-25  PRE-FIXADOS
01/01/2008      25/10/2007      2008-01-01 2007-10-25  PRE-FIXADOS
01/01/2009      25/10/2007      2009-01-01 2007-10-25  PRE-FIXADOS
01/07/2009      25/10/2007      2009-07-01 2007-10-25  PRE-FIXADOS
01/10/2009      25/10/2007      2009-10-01 2007-10-25  PRE-FIXADOS
01/01/2010      25/10/2007      2010-01-01 2007-10-25  PRE-FIXADOS
01/10/2008      25/10/2007      2008-10-01 2007-10-25  PRE-FIXADOS
01/04/2008      25/10/2007      2008-04-01 2007-10-25  PRE-FIXADOS
01/10/2009      24/10/2007      2009-10-01 2007-10-24  PRE-FIXADOS
01/07/2009      24/10/2007      2009-07-01 2007-10-24  PRE-FIXADOS
...                                    ...        ...          ...
01/01/2014      17/08/2011      2014-01-01 2011-08-17  PRE-FIXADOS
01/01/2015      17/08/2011      2015-01-01 2011-08-17  PRE-FIXADOS
                16/08/2011      2015-01-01 2011-08-16  PRE-FIXADOS
01/01/2013      16/08/2011      2013-01-01 2011-08-16  PRE-FIXADOS
01/01/2012      16/08/2011      2012-01-01 2011-08-16  PRE-FIXADOS
01/01/2014      16/08/2011      2014-01-01 2011-08-16  PRE-FIXADOS
01/01/2013      15/08/2011      2013-01-01 2011-08-15  PRE-FIXADOS
01/01/2014      15/08/2011      2014-01-01 2011-08-15  PRE-FIXADOS
01/01/2015      15/08/2011      2015-01-01 2011-08-15  PRE-FIXADOS
01/01/2012      15/08/2011      2012-01-01 2011-08-15  PRE-FIXADOS

[27805 rows x 8 columns]

In [128]:
for i, row in prefixado.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    prefixado.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

/var/folders/cx/md507_zx4ybf51hwf3zqkzbh0000gn/T/ipykernel_47192/913561871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prefixado.at[i,'dt_update'] = ifor_val

In [129]:
prefixado

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
01/07/2008      25/10/2007              11.34             11.38
01/01/2008      25/10/2007              11.16             11.19
01/01/2009      25/10/2007              11.54             11.58
01/07/2009      25/10/2007              11.73             11.78
01/10/2009      25/10/2007              11.77             11.82
01/01/2010      25/10/2007              11.77             11.83
01/10/2008      25/10/2007              11.45             11.49
01/04/2008      25/10/2007              11.23             11.26
01/10/2009      24/10/2007              11.66             11.71
01/07/2009      24/10/2007              11.61             11.66
...                                       ...               ...
01/01/2014      17/08/2011              11.97             12.03
01/01/2015      17/08/2011              12.02             12.08
                16/08/2011              12.10             12.16
01/01/2013      16/08/2011              11.97             12.01
01/01/2012      16/08/2011              12.34             12.37
01/01/2014      16/08/2011              12.02             12.08
01/01/2013      15/08/2011              11.95             11.99
01/01/2014      15/08/2011              12.05             12.11
01/01/2015      15/08/2011              12.13             12.19
01/01/2012      15/08/2011              12.32             12.35

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
01/07/2008      25/10/2007           931.28          931.06         930.66
01/01/2008      25/10/2007           981.69          981.65         981.23
01/01/2009      25/10/2007           878.84          878.47         878.08
01/07/2009      25/10/2007           831.22          830.60         830.23
01/10/2009      25/10/2007           807.22          806.52         806.17
01/01/2010      25/10/2007           785.07          784.16         783.81
01/10/2008      25/10/2007           904.62          904.32         903.93
01/04/2008      25/10/2007           956.62          956.51         956.11
01/10/2009      24/10/2007           808.39          807.70         807.34
01/07/2009      24/10/2007           832.34          831.72         831.36
...                                     ...             ...            ...
01/01/2014      17/08/2011           765.02          764.05         763.71
01/01/2015      17/08/2011           681.90          680.67         680.36
                16/08/2011           679.95          678.73         678.42
01/01/2013      16/08/2011           856.59          856.18         855.79
01/01/2012      16/08/2011           957.52          957.42         956.98
01/01/2014      16/08/2011           763.87          762.90         762.55
01/01/2013      15/08/2011           856.42          856.00         855.62
01/01/2014      15/08/2011           763.04          762.07         761.72
01/01/2015      15/08/2011           679.03          677.80         677.49
01/01/2012      15/08/2011           957.14          957.05         956.60

                           Data_Vencimento  Data_Base         Tipo  \
Data Vencimento Data Base
01/07/2008      25/10/2007      2008-07-01 2007-10-25  PRE-FIXADOS
01/01/2008      25/10/2007      2008-01-01 2007-10-25  PRE-FIXADOS
01/01/2009      25/10/2007      2009-01-01 2007-10-25  PRE-FIXADOS
01/07/2009      25/10/2007      2009-07-01 2007-10-25  PRE-FIXADOS
01/10/2009      25/10/2007      2009-10-01 2007-10-25  PRE-FIXADOS
01/01/2010      25/10/2007      2010-01-01 2007-10-25  PRE-FIXADOS
01/10/2008      25/10/2007      2008-10-01 2007-10-25  PRE-FIXADOS
01/04/2008      25/10/2007      2008-04-01 2007-10-25  PRE-FIXADOS
01/10/2009      24/10/2007      2009-10-01 2007-10-24  PRE-FIXADOS
01/07/2009      24/10/2007      2009-07-01 2007-10-24  PRE-FIXADOS
...                                    ...        ...          ...
01/01/2014      17/08/2011      2014-01-01 2011-08-17  PRE-FIXADOS
01/01/2015      17/08/2011      2015-01-01 2011-08-17  PRE-FIXADOS
                16/08/2011      2015-01-01 2011-08-16  PRE-FIXADOS
01/01/2013      16/08/2011      2013-01-01 2011-08-16  PRE-FIXADOS
01/01/2012      16/08/2011      2012-01-01 2011-08-16  PRE-FIXADOS
01/01/2014      16/08/2011      2014-01-01 2011-08-16  PRE-FIXADOS
01/01/2013      15/08/2011      2013-01-01 2011-08-15  PRE-FIXADOS
01/01/2014      15/08/2011      2014-01-01 2011-08-15  PRE-FIXADOS
01/01/2015      15/08/2011      2015-01-01 2011-08-15  PRE-FIXADOS
01/01/2012      15/08/2011      2012-01-01 2011-08-15  PRE-FIXADOS

                                            dt_update
Data Vencimento Data Base
01/07/2008      25/10/2007 2026-06-21 16:14:14.694595
01/01/2008      25/10/2007 2026-06-21 16:14:14.695691
01/01/2009      25/10/2007 2026-06-21 16:14:14.695884
01/07/2009      25/10/2007 2026-06-21 16:14:14.696056
01/10/2009      25/10/2007 2026-06-21 16:14:14.696224
01/01/2010      25/10/2007 2026-06-21 16:14:14.696411
01/10/2008      25/10/2007 2026-06-21 16:14:14.696610
01/04/2008      25/10/2007 2026-06-21 16:14:14.696795
01/10/2009      24/10/2007 2026-06-21 16:14:14.696960
01/07/2009      24/10/2007 2026-06-21 16:14:14.697122
...                                               ...
01/01/2014      17/08/2011 2026-06-21 16:14:18.973665
01/01/2015      17/08/2011 2026-06-21 16:14:18.973822
                16/08/2011 2026-06-21 16:14:18.973974
01/01/2013      16/08/2011 2026-06-21 16:14:18.974126
01/01/2012      16/08/2011 2026-06-21 16:14:18.974279
01/01/2014      16/08/2011 2026-06-21 16:14:18.974431
01/01/2013      15/08/2011 2026-06-21 16:14:18.974584
01/01/2014      15/08/2011 2026-06-21 16:14:18.974739
01/01/2015      15/08/2011 2026-06-21 16:14:18.974892
01/01/2012      15/08/2011 2026-06-21 16:14:18.975044

[27805 rows x 9 columns]

Busca os IPCAs

In [130]:
ipca = titulos.loc[('Tesouro IPCA+')]
ipca['Tipo'] = "IPCA"

/var/folders/cx/md507_zx4ybf51hwf3zqkzbh0000gn/T/ipykernel_47192/3738600803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca['Tipo'] = "IPCA"

In [131]:
for i, row in ipca.iterrows():
    ifor_val = datetime.now() - timedelta(hours=1, minutes=0)
    ipca.at[i,'dt_update'] = ifor_val
    time.sleep(1/10000)

/var/folders/cx/md507_zx4ybf51hwf3zqkzbh0000gn/T/ipykernel_47192/3161604202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ipca.at[i,'dt_update'] = ifor_val

In [132]:
ipca

                            Taxa Compra Manha  Taxa Venda Manha  \
Data Vencimento Data Base
15/08/2024      25/10/2007               6.29              6.37
15/05/2015      25/10/2007               7.19              7.25
15/08/2024      24/10/2007               6.30              6.38
15/05/2015      24/10/2007               7.12              7.18
15/08/2024      28/09/2007               6.38              6.46
15/05/2015      28/09/2007               6.79              6.85
15/08/2024      27/09/2007               6.37              6.45
15/05/2015      27/09/2007               6.79              6.85
15/08/2024      26/09/2007               6.38              6.46
15/05/2015      26/09/2007               6.80              6.86
...                                       ...               ...
                28/12/2010               6.12              6.16
15/05/2035      18/08/2011               6.03              6.13
15/08/2024      18/08/2011               6.12              6.20
15/05/2015      18/08/2011               6.11              6.15
15/08/2024      17/08/2011               6.17              6.25
15/05/2015      17/08/2011               6.21              6.25
15/05/2035      17/08/2011               6.05              6.15
                16/08/2011               6.09              6.19
15/08/2024      16/08/2011               6.23              6.31
15/05/2015      16/08/2011               6.29              6.33

                            PU Compra Manha  PU Venda Manha  PU Base Manha  \
Data Vencimento Data Base
15/08/2024      25/10/2007           601.15          593.62         593.44
15/05/2015      25/10/2007           989.75          985.59         985.25
15/08/2024      24/10/2007           600.11          592.60         592.40
15/05/2015      24/10/2007           994.45          990.27         989.91
15/08/2024      28/09/2007           589.33          581.93         581.64
15/05/2015      28/09/2007          1011.96         1007.65        1007.14
15/08/2024      27/09/2007           589.98          582.56         582.37
15/05/2015      27/09/2007          1011.45         1007.14        1006.79
15/08/2024      26/09/2007           588.85          581.46         581.26
15/05/2015      26/09/2007          1010.38         1006.08        1005.73
...                                     ...             ...            ...
                28/12/2010          1521.44         1518.94        1518.29
15/05/2035      18/08/2011           515.76          504.38         504.22
15/08/2024      18/08/2011           955.05          945.79         945.48
15/05/2015      18/08/2011          1651.53         1649.21        1648.67
15/08/2024      17/08/2011           948.94          939.73         939.42
15/05/2015      17/08/2011          1645.20         1642.89        1642.34
15/05/2035      17/08/2011           513.29          501.98         501.81
                16/08/2011           508.57          497.36         497.20
15/08/2024      16/08/2011           941.72          932.58         932.27
15/05/2015      16/08/2011          1640.04         1637.73        1637.19

                           Data_Vencimento  Data_Base  Tipo  \
Data Vencimento Data Base
15/08/2024      25/10/2007      2024-08-15 2007-10-25  IPCA
15/05/2015      25/10/2007      2015-05-15 2007-10-25  IPCA
15/08/2024      24/10/2007      2024-08-15 2007-10-24  IPCA
15/05/2015      24/10/2007      2015-05-15 2007-10-24  IPCA
15/08/2024      28/09/2007      2024-08-15 2007-09-28  IPCA
15/05/2015      28/09/2007      2015-05-15 2007-09-28  IPCA
15/08/2024      27/09/2007      2024-08-15 2007-09-27  IPCA
15/05/2015      27/09/2007      2015-05-15 2007-09-27  IPCA
15/08/2024      26/09/2007      2024-08-15 2007-09-26  IPCA
15/05/2015      26/09/2007      2015-05-15 2007-09-26  IPCA
...                                    ...        ...   ...
                28/12/2010      2015-05-15 2010-12-28  IPCA
15/05/2035      18/08/2011      2035-05-15 2011-08-18  IPCA
15/08/2024      18/08/2011      2024-08-15 2011-08-18  IPCA
15/05/2015      18/08/2011      2015-05-15 2011-08-18  IPCA
15/08/2024      17/08/2011      2024-08-15 2011-08-17  IPCA
15/05/2015      17/08/2011      2015-05-15 2011-08-17  IPCA
15/05/2035      17/08/2011      2035-05-15 2011-08-17  IPCA
                16/08/2011      2035-05-15 2011-08-16  IPCA
15/08/2024      16/08/2011      2024-08-15 2011-08-16  IPCA
15/05/2015      16/08/2011      2015-05-15 2011-08-16  IPCA

                                            dt_update
Data Vencimento Data Base
15/08/2024      25/10/2007 2026-06-21 16:14:19.038583
15/05/2015      25/10/2007 2026-06-21 16:14:19.039545
15/08/2024      24/10/2007 2026-06-21 16:14:19.039724
15/05/2015      24/10/2007 2026-06-21 16:14:19.039883
15/08/2024      28/09/2007 2026-06-21 16:14:19.040038
15/05/2015      28/09/2007 2026-06-21 16:14:19.040190
15/08/2024      27/09/2007 2026-06-21 16:14:19.040344
15/05/2015      27/09/2007 2026-06-21 16:14:19.040497
15/08/2024      26/09/2007 2026-06-21 16:14:19.040647
15/05/2015      26/09/2007 2026-06-21 16:14:19.040798
...                                               ...
                28/12/2010 2026-06-21 16:14:21.873030
15/05/2035      18/08/2011 2026-06-21 16:14:21.873184
15/08/2024      18/08/2011 2026-06-21 16:14:21.873337
15/05/2015      18/08/2011 2026-06-21 16:14:21.873489
15/08/2024      17/08/2011 2026-06-21 16:14:21.873641
15/05/2015      17/08/2011 2026-06-21 16:14:21.873793
15/05/2035      17/08/2011 2026-06-21 16:14:21.873944
                16/08/2011 2026-06-21 16:14:21.874096
15/08/2024      16/08/2011 2026-06-21 16:14:21.874249
15/05/2015      16/08/2011 2026-06-21 16:14:21.874402

[18410 rows x 9 columns]

In [133]:
#frames = [prefixado, ipca]
#todos = pd.concat(frames)
ipca = ipca.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})
prefixado = prefixado.rename(columns={"Data Vencimento": "DataVencimento", "Data Base": "Data_Base", "Taxa Compra Manha": "CompraManha", "Taxa Venda Manha": "VendaManha", "PU Compra Manha": "PUCompraManha", "PU Venda Manha": "PUVendaManha",  "PU Base Manha": "PUBaseManha"})

In [134]:
ipca

                            CompraManha  VendaManha  PUCompraManha  \
Data Vencimento Data Base
15/08/2024      25/10/2007         6.29        6.37         601.15
15/05/2015      25/10/2007         7.19        7.25         989.75
15/08/2024      24/10/2007         6.30        6.38         600.11
15/05/2015      24/10/2007         7.12        7.18         994.45
15/08/2024      28/09/2007         6.38        6.46         589.33
15/05/2015      28/09/2007         6.79        6.85        1011.96
15/08/2024      27/09/2007         6.37        6.45         589.98
15/05/2015      27/09/2007         6.79        6.85        1011.45
15/08/2024      26/09/2007         6.38        6.46         588.85
15/05/2015      26/09/2007         6.80        6.86        1010.38
...                                 ...         ...            ...
                28/12/2010         6.12        6.16        1521.44
15/05/2035      18/08/2011         6.03        6.13         515.76
15/08/2024      18/08/2011         6.12        6.20         955.05
15/05/2015      18/08/2011         6.11        6.15        1651.53
15/08/2024      17/08/2011         6.17        6.25         948.94
15/05/2015      17/08/2011         6.21        6.25        1645.20
15/05/2035      17/08/2011         6.05        6.15         513.29
                16/08/2011         6.09        6.19         508.57
15/08/2024      16/08/2011         6.23        6.31         941.72
15/05/2015      16/08/2011         6.29        6.33        1640.04

                            PUVendaManha  PUBaseManha Data_Vencimento  \
Data Vencimento Data Base
15/08/2024      25/10/2007        593.62       593.44      2024-08-15
15/05/2015      25/10/2007        985.59       985.25      2015-05-15
15/08/2024      24/10/2007        592.60       592.40      2024-08-15
15/05/2015      24/10/2007        990.27       989.91      2015-05-15
15/08/2024      28/09/2007        581.93       581.64      2024-08-15
15/05/2015      28/09/2007       1007.65      1007.14      2015-05-15
15/08/2024      27/09/2007        582.56       582.37      2024-08-15
15/05/2015      27/09/2007       1007.14      1006.79      2015-05-15
15/08/2024      26/09/2007        581.46       581.26      2024-08-15
15/05/2015      26/09/2007       1006.08      1005.73      2015-05-15
...                                  ...          ...             ...
                28/12/2010       1518.94      1518.29      2015-05-15
15/05/2035      18/08/2011        504.38       504.22      2035-05-15
15/08/2024      18/08/2011        945.79       945.48      2024-08-15
15/05/2015      18/08/2011       1649.21      1648.67      2015-05-15
15/08/2024      17/08/2011        939.73       939.42      2024-08-15
15/05/2015      17/08/2011       1642.89      1642.34      2015-05-15
15/05/2035      17/08/2011        501.98       501.81      2035-05-15
                16/08/2011        497.36       497.20      2035-05-15
15/08/2024      16/08/2011        932.58       932.27      2024-08-15
15/05/2015      16/08/2011       1637.73      1637.19      2015-05-15

                            Data_Base  Tipo                  dt_update
Data Vencimento Data Base
15/08/2024      25/10/2007 2007-10-25  IPCA 2026-06-21 16:14:19.038583
15/05/2015      25/10/2007 2007-10-25  IPCA 2026-06-21 16:14:19.039545
15/08/2024      24/10/2007 2007-10-24  IPCA 2026-06-21 16:14:19.039724
15/05/2015      24/10/2007 2007-10-24  IPCA 2026-06-21 16:14:19.039883
15/08/2024      28/09/2007 2007-09-28  IPCA 2026-06-21 16:14:19.040038
15/05/2015      28/09/2007 2007-09-28  IPCA 2026-06-21 16:14:19.040190
15/08/2024      27/09/2007 2007-09-27  IPCA 2026-06-21 16:14:19.040344
15/05/2015      27/09/2007 2007-09-27  IPCA 2026-06-21 16:14:19.040497
15/08/2024      26/09/2007 2007-09-26  IPCA 2026-06-21 16:14:19.040647
15/05/2015      26/09/2007 2007-09-26  IPCA 2026-06-21 16:14:19.040798
...                               ...   ...                        ...
                28/12/2010 2010-12-28  IPCA 2026-06-21 16:14:21.873030
15/05/2035      18/08/2011 2011-08-18  IPCA 2026-06-21 16:14:21.873184
15/08/2024      18/08/2011 2011-08-18  IPCA 2026-06-21 16:14:21.873337
15/05/2015      18/08/2011 2011-08-18  IPCA 2026-06-21 16:14:21.873489
15/08/2024      17/08/2011 2011-08-17  IPCA 2026-06-21 16:14:21.873641
15/05/2015      17/08/2011 2011-08-17  IPCA 2026-06-21 16:14:21.873793
15/05/2035      17/08/2011 2011-08-17  IPCA 2026-06-21 16:14:21.873944
                16/08/2011 2011-08-16  IPCA 2026-06-21 16:14:21.874096
15/08/2024      16/08/2011 2011-08-16  IPCA 2026-06-21 16:14:21.874249
15/05/2015      16/08/2011 2011-08-16  IPCA 2026-06-21 16:14:21.874402

[18410 rows x 9 columns]

Grava os dados no Banco de Dados

In [135]:
connection_string = "postgresql://postgres:password@localhost:5432/postgres"

In [136]:
engine = create_engine(connection_string)

In [137]:
ipca.to_sql("tesouro_ipca", con=engine, if_exists="append", index=False)
prefixado.to_sql("tesouro_pre", con=engine, if_exists="append", index=False)

805